---
- name: "Create docker volume {{ docker_volume_name }}"
  docker_volume:
    name: "{{ docker_volume_name }}"
  when: docker_volume_name is defined

- name: Copy backup/restore scripts
  template:
    src: docker-volume.j2
    dest: "{{ item }}"
    mode: +x
  loop:
    - "{{ docker_volume_executable.bin }}"

- name: Register docker volume backup job
  cron:
    name: "Backup job {{ item.id }}"
    hour: "{{ item.hour }}"
    minute: "{{ item.minute | default(59 | random(seed=item.id)) }}"
    job: "{{ item.cli }}"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ item.state | default('present') }}"
  with_items:
    - "{{ docker_volume_backup_cron_job }}"
  when: docker_volume_for_container is defined and docker_volume_backup_dirs | length > 0
